INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('abaudichon13', 1, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('abaudichon13', 2, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('abidewel18', 3, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('abidewel18', 4, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('abrierley37', 5, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('abrierley37', 6, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('abullente', 7, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('abullente', 8, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('abullerwell3x', 9, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('abullerwell3x', 10, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('afullstone5b', 11, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('afullstone5b', 12, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('agisborne5d', 13, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('agisborne5d', 14, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('ahapke2v', 15, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('ahapke2v', 16, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('aleyden8', 17, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('aleyden8', 18, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('amackill45', 19, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('amackill45', 20, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('amacness1q', 21, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('amacness1q', 22, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('apack1u', 23, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('apack1u', 24, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('apellantk', 25, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('apellantk', 26, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('arelf29', 27, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('arelf29', 28, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('aspikeings2w', 29, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('aspikeings2w', 30, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('baudenis2j', 31, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('baudenis2j', 32, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('bboerder35', 33, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('bboerder35', 34, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('bchumley4u', 35, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('bchumley4u', 36, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('bdouty4d', 37, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('bdouty4d', 38, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('bportchmouth1c', 39, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('bportchmouth1c', 40, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('bswoffer12', 41, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('bswoffer12', 42, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('bthornberm', 43, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('bthornberm', 44, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('bworboy4', 45, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('bworboy4', 46, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('cbieverp', 47, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('cbieverp', 48, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('cbrotherhed3c', 49, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('cbrotherhed3c', 50, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('cdollar22', 51, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('cdollar22', 52, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('cfley36', 53, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('cfley36', 54, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('chilleng', 55, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('chilleng', 56, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('clegood5e', 57, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('clegood5e', 58, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('cmccard3t', 59, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('cmctrustam24', 1, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('cmctrustam24', 2, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('cmoody4g', 3, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('cmoody4g', 4, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('croslenu', 5, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('croslenu', 6, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('cshelly38', 7, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('cshelly38', 8, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('dbalbeck1r', 9, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('dbalbeck1r', 10, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('dchattell4r', 11, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('dchattell4r', 12, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('ddempsey16', 13, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('ddempsey16', 14, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('dflament20', 15, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('dflament20', 16, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('dgillfillan2z', 17, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('dgillfillan2z', 18, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('dhewes3r', 19, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('dhewes3r', 20, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('dmcgivena1p', 21, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('dmcgivena1p', 22, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('dnarracott3', 23, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('dnarracott3', 24, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('dnorris2g', 25, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('dnorris2g', 26, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('dollander3v', 27, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('dollander3v', 28, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('dparram43', 29, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('dparram43', 30, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('dpumfrey1j', 31, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('dpumfrey1j', 32, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('dtolotti6', 33, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('dtolotti6', 34, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('dvarsey51', 35, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('dvarsey51', 36, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('dwilkes3g', 37, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('dwilkes3g', 38, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('ebernt54', 39, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('ebernt54', 40, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('eemeline3l', 41, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('eemeline3l', 42, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('efutterb', 43, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('efutterb', 44, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('eramas2c', 45, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('eramas2c', 46, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('etumini4v', 47, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('etumini4v', 48, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('fantognozzii2q', 49, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('fantognozzii2q', 50, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('fwitherow17', 51, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('fwitherow17', 52, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('gballchinq', 53, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('gballchinq', 54, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('gbrabender1w', 55, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('gbrabender1w', 56, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('gcrosskell3p', 57, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('gcrosskell3p', 58, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('gde40', 59, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('ghollingsbyi', 1, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('ghollingsbyi', 2, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('gkyneton4z', 3, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('gkyneton4z', 4, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('gnulty1m', 5, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('gnulty1m', 6, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('gshimuk1z', 7, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('gshimuk1z', 8, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('gtolomei1o', 9, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('gtolomei1o', 10, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('gwharf4y', 11, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('gwharf4y', 12, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('hcardenoso1e', 13, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('hcardenoso1e', 14, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('hcheel9', 15, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('hcheel9', 16, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('hchippendaleo', 17, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('hchippendaleo', 18, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('hconnealy2y', 19, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('hconnealy2y', 20, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('hde3d', 21, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('hde3d', 22, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('hfisbburner', 23, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('hfisbburner', 24, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('hfolger4c', 25, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('hfolger4c', 26, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('hfryatt41', 27, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('hfryatt41', 28, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('hfryett3k', 29, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('hfryett3k', 30, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('hmckeighan2', 31, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('hmckeighan2', 32, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('hpersicke31', 33, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('hpersicke31', 34, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('hsibthorpea', 35, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('hsibthorpea', 36, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('irookes1v', 37, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('irookes1v', 38, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('iwanklin2o', 39, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('iwanklin2o', 40, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('jbroggini56', 41, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('jbroggini56', 42, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('jdarville1t', 43, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('jdarville1t', 44, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('jduff23', 45, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('jduff23', 46, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('jerbain2l', 47, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('jerbain2l', 48, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('jhowgego52', 49, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('jhowgego52', 50, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('jkapiloff5a', 51, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('jkapiloff5a', 52, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('jkelsell2t', 53, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('jkelsell2t', 54, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('jletessier5f', 55, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('jletessier5f', 56, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('jlethbrig4q', 57, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('jlethbrig4q', 58, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('jmacvaugh4k', 59, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('jmeneer3m', 1, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('jmeneer3m', 2, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('jprydie3n', 3, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('jprydie3n', 4, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('jshelp58', 5, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('jshelp58', 6, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('jstainer42', 7, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('jstainer42', 8, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('jstenning2e', 9, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('jstenning2e', 10, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('jzucker4x', 11, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('jzucker4x', 12, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('kabson4p', 13, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('kabson4p', 14, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('kambrogelli1a', 15, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('kambrogelli1a', 16, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('kbrumfield1x', 17, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('kbrumfield1x', 18, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('kdumphries14', 19, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('kdumphries14', 20, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('kgehricke3h', 21, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('kgehricke3h', 22, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('kgemmill2s', 23, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('kgemmill2s', 24, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('kgreenin3e', 25, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('kgreenin3e', 26, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('kjanko1', 27, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('kjanko1', 28, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('kkimblen39', 29, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('kkimblen39', 30, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('klabrom5j', 31, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('klabrom5j', 32, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('kmeany26', 33, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('kmeany26', 34, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('kpallentc', 35, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('kpallentc', 36, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('kwordsley1y', 37, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('kwordsley1y', 38, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('lblazejz', 39, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('lblazejz', 40, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('lbuckleigh3q', 41, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('lbuckleigh3q', 42, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('lcaillou4f', 43, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('lcaillou4f', 44, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('lcoppin34', 45, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('lcoppin34', 46, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('ldesmond4a', 47, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('ldesmond4a', 48, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('learles5h', 49, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('learles5h', 50, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('lhannen4n', 51, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('lhannen4n', 52, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('lklimkes', 53, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('lklimkes', 54, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('lrushmere5c', 55, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('lrushmere5c', 56, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('lspatoni1l', 57, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('lspatoni1l', 58, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('lwyld2h', 59, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('mattew19', 1, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('mattew19', 2, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('mdovydenas59', 3, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('mdovydenas59', 4, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('mgauthorpp3u', 5, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('mgauthorpp3u', 6, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('mhighman4l', 7, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('mhighman4l', 8, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('mlocke11', 9, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('mlocke11', 10, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('mlynam53', 11, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('mlynam53', 12, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('mpossel4e', 13, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('mpossel4e', 14, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('msaipy2i', 15, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('msaipy2i', 16, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('mtauntonl', 17, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('mtauntonl', 18, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('mtitmuss28', 19, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('mtitmuss28', 20, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('mwheeler4m', 21, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('mwheeler4m', 22, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('mwhiley3w', 23, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('mwhiley3w', 24, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('nfrawley4j', 25, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('nfrawley4j', 26, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('obilld', 27, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('obilld', 28, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('odartanj', 29, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('odartanj', 30, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('omcgiveen2x', 31, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('omcgiveen2x', 32, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('omcmenamy7', 33, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('omcmenamy7', 34, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('onottle1b', 35, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('onottle1b', 36, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('opersent3z', 37, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('opersent3z', 38, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('oroyan32', 39, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('oroyan32', 40, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('osadgrovey', 41, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('osadgrovey', 42, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('othouless30', 43, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('othouless30', 44, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('pcowlas49', 45, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('pcowlas49', 46, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('plef', 47, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('plef', 48, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('prack4w', 49, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('prack4w', 50, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('qdaouse15', 51, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('qdaouse15', 52, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('qgrievson5g', 53, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('qgrievson5g', 54, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('rbemwell3b', 55, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('rbemwell3b', 56, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('rblown2u', 57, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('rblown2u', 58, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('rcanto27', 59, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('reverleigh2n', 1, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('reverleigh2n', 2, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('rgosz25', 3, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('rgosz25', 4, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('rgrimbleby2r', 5, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('rgrimbleby2r', 6, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('rhimsworth1d', 7, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('rhimsworth1d', 8, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('rhudd2d', 9, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('rhudd2d', 10, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('rlaidelt', 11, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('rlaidelt', 12, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('rsuggett1g', 13, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('rsuggett1g', 14, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('rworssamh', 15, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('rworssamh', 16, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('sbedminsterx', 17, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('sbedminsterx', 18, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('sdessant46', 19, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('sdessant46', 20, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('sdrewclifton1s', 21, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('sdrewclifton1s', 22, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('sdyble57', 23, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('sdyble57', 24, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('sgoalley3o', 25, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('sgoalley3o', 26, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('sgreatbachw', 27, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('sgreatbachw', 28, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('sgreenleaf5', 29, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('sgreenleaf5', 30, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('sjenteau3s', 31, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('sjenteau3s', 32, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('slesor50', 33, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('slesor50', 34, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('smorse4t', 35, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('smorse4t', 36, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('sosmund55', 37, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('sosmund55', 38, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('soventon4o', 39, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('soventon4o', 40, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('spretiousv', 41, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('spretiousv', 42, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('srohan1i', 43, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('srohan1i', 44, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('sstebbins5i', 45, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('sstebbins5i', 46, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('tbeever1h', 47, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('tbeever1h', 48, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('tbettenay33', 49, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('tbettenay33', 50, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('tclapp44', 51, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('tclapp44', 52, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('tdurninn', 53, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('tdurninn', 54, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('tglazzard4b', 55, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('tglazzard4b', 56, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('tkerman1n', 57, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('tkerman1n', 58, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('tknowlman2m', 59, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('tkopecka3y', 1, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('tkopecka3y', 2, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('tloughrey3i', 3, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('tloughrey3i', 4, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('tmacourek10', 5, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('tmacourek10', 6, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('tmckew2p', 7, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('tmckew2p', 8, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('trubinowitz4s', 9, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('trubinowitz4s', 10, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('tschneider3j', 11, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('tschneider3j', 12, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('ucowperthwaite2a', 13, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('ucowperthwaite2a', 14, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('uo2k', 15, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('uo2k', 16, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('vbavester48', 17, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('vbavester48', 18, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('vmccarlie1k', 19, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('vmccarlie1k', 20, 'going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('wambrozewicz0', 21, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('wambrozewicz0', 22, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('wbradberry21', 23, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('wbradberry21', 24, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('wbrellin2f', 25, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('wbrellin2f', 26, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('wkneafsey4i', 27, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('wkneafsey4i', 28, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('wlampl4h', 29, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('wlampl4h', 30, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('wmannering3f', 31, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('wmannering3f', 32, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('wminet1f', 33, 'not going');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('wminet1f', 34, null);
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('wroyds2b', 35, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('wroyds2b', 36, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('xgennerich3a', 37, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('xgennerich3a', 38, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('zsiemens47', 39, 'maybe');
INSERT INTO eventt_subscription (usert_handle, eventt_id, rsvp_status) VALUES ('zsiemens47', 40, null);
