INSERT INTO page (page_handle, description, title, usert_handle) VALUES ('dbeinke0', 'leverage open-source convergence', 'Willard', 'wambrozewicz0');
INSERT INTO page (page_handle, description, title, usert_handle) VALUES ('owharlton1', 'generate end-to-end deliverables', 'Diamonds Are Forever', 'kjanko1');
INSERT INTO page (page_handle, description, title, usert_handle) VALUES ('ggentry2', 'exploit transparent infomediaries', 'Tiger and the Snow, The (La tigre e la neve)', 'hmckeighan2');
INSERT INTO page (page_handle, description, title, usert_handle) VALUES ('awinyard3', 'expedite distributed schemas', 'Skinwalkers', 'dnarracott3');
INSERT INTO page (page_handle, description, title, usert_handle) VALUES ('kswanwick4', 'maximize best-of-breed models', 'Man Apart, A', 'bworboy4');
INSERT INTO page (page_handle, description, title, usert_handle) VALUES ('vweatherill5', 'utilize compelling content', 'Pokemon 4 Ever (a.k.a. Pokémon 4: The Movie)', 'sgreenleaf5');
INSERT INTO page (page_handle, description, title, usert_handle) VALUES ('dbecerro6', 'extend efficient portals', 'Don McKay', 'dtolotti6');
INSERT INTO page (page_handle, description, title, usert_handle) VALUES ('ckolak7', 'maximize next-generation content', 'Jerichow', 'omcmenamy7');
INSERT INTO page (page_handle, description, title, usert_handle) VALUES ('noxer8', 'incubate world-class content', 'Ann Carver''s Profession', 'aleyden8');
INSERT INTO page (page_handle, description, title, usert_handle) VALUES ('hfishenden9', 'leverage B2B systems', 'Employee of the Month', 'hcheel9');
INSERT INTO page (page_handle, description, title, usert_handle) VALUES ('pbaxendalea', 'target viral portals', 'They All Lie', 'hsibthorpea');
INSERT INTO page (page_handle, description, title, usert_handle) VALUES ('abeslierb', 'morph one-to-one action-items', 'Wish Upon a Star', 'efutterb');
INSERT INTO page (page_handle, description, title, usert_handle) VALUES ('vjuarezc', 'envisioneer ubiquitous technologies', 'Von Ryan''s Express', 'kpallentc');
INSERT INTO page (page_handle, description, title, usert_handle) VALUES ('etakkosd', 'whiteboard strategic functionalities', 'Adam''s Apples (Adams æbler)', 'obilld');
INSERT INTO page (page_handle, description, title, usert_handle) VALUES ('cdanzige', 'whiteboard enterprise markets', '8 Heads in a Duffel Bag', 'abullente');
INSERT INTO page (page_handle, description, title, usert_handle) VALUES ('dpidcockf', 'exploit customized e-markets', 'The Brave Little Toaster Goes to Mars', 'plef');
INSERT INTO page (page_handle, description, title, usert_handle) VALUES ('lgung', 'utilize proactive functionalities', 'Yolanda and the Thief', 'chilleng');
INSERT INTO page (page_handle, description, title, usert_handle) VALUES ('hsimmigh', 'mesh distributed niches', 'Monster, The (Mostro, Il)', 'rworssamh');
INSERT INTO page (page_handle, description, title, usert_handle) VALUES ('agopsalli', 'redefine synergistic schemas', 'Broadway Melody of 1940', 'ghollingsbyi');
INSERT INTO page (page_handle, description, title, usert_handle) VALUES ('ewillcockj', 'target dynamic deliverables', 'Pisum L.', 'odartanj');
INSERT INTO page (page_handle, description, title, usert_handle) VALUES ('lderringtonk', 'engage granular technologies', 'Heterodermia neglecta Lendemer, R.C. Harris & E.A. Tripp', 'apellantk');
INSERT INTO page (page_handle, description, title, usert_handle) VALUES ('jreadl', 'transform proactive users', 'Hesperevax acaulis (Kellogg) Greene', 'mtauntonl');
INSERT INTO page (page_handle, description, title, usert_handle) VALUES ('cbullochm', 'unleash collaborative functionalities', 'Styrax platanifolius Engelm. ssp. texanus (Cory) P.W. Fritsch', 'bthornberm');
INSERT INTO page (page_handle, description, title, usert_handle) VALUES ('rscolen', 'extend extensible systems', 'Leucojum L.', 'tdurninn');
INSERT INTO page (page_handle, description, title, usert_handle) VALUES ('bbarnfathero', 'productize 24/365 e-tailers', 'Achillea filipendulina Lam.', 'hchippendaleo');
INSERT INTO page (page_handle, description, title, usert_handle) VALUES ('obradlyp', 'synthesize next-generation e-services', 'Hedyotis schlechtendahliana Steud.', 'cbieverp');
INSERT INTO page (page_handle, description, title, usert_handle) VALUES ('rrevittq', 'incubate value-added e-markets', 'Cymbopogon jwarancusa (Jones) Schult.', 'gballchinq');
INSERT INTO page (page_handle, description, title, usert_handle) VALUES ('mmudger', 'enable customized infomediaries', 'Coriandrum sativum L.', 'hfisbburner');
INSERT INTO page (page_handle, description, title, usert_handle) VALUES ('eboughtons', 'integrate enterprise infrastructures', 'Mitracarpus portoricensis (Urb.) Urb.', 'lklimkes');
INSERT INTO page (page_handle, description, title, usert_handle) VALUES ('nlevingst', 'target extensible functionalities', 'Altai State Medical University', 'rlaidelt');
INSERT INTO page (page_handle, description, title, usert_handle) VALUES ('bmerrileesu', 'monetize virtual web-readiness', 'Columbia Southern University', 'croslenu');
INSERT INTO page (page_handle, description, title, usert_handle) VALUES ('bmelbyv', 'evolve 24/7 partnerships', 'Marietta College', 'spretiousv');
INSERT INTO page (page_handle, description, title, usert_handle) VALUES ('vskynerw', 'reintermediate real-time channels', 'University of North Alabama', 'sgreatbachw');
INSERT INTO page (page_handle, description, title, usert_handle) VALUES ('bdillestonex', 'visualize extensible synergies', 'Aga Khan University', 'sbedminsterx');
INSERT INTO page (page_handle, description, title, usert_handle) VALUES ('tvasilechkoy', 'embrace B2B eyeballs', 'Peking University', 'osadgrovey');
INSERT INTO page (page_handle, description, title, usert_handle) VALUES ('mbrittonz', 'synergize innovative e-tailers', 'University of California, Davis', 'lblazejz');
INSERT INTO page (page_handle, description, title, usert_handle) VALUES ('csiebert10', 'revolutionize mission-critical paradigms', 'Shiraz Payamnoor University', 'tmacourek10');
INSERT INTO page (page_handle, description, title, usert_handle) VALUES ('iskokoe11', 'orchestrate visionary web-readiness', 'University of Architecture, Civil Engineering and Geodesy', 'mlocke11');
INSERT INTO page (page_handle, description, title, usert_handle) VALUES ('fdumphries12', 'envisioneer cutting-edge niches', 'University of Veterinary Science', 'bswoffer12');
INSERT INTO page (page_handle, description, title, usert_handle) VALUES ('smcasparan13', 'streamline vertical metrics', 'Marchex, Inc.', 'abaudichon13');
INSERT INTO page (page_handle, description, title, usert_handle) VALUES ('btellenbroker14', 'incentivize intuitive e-services', 'Eaton Vance Enhance Equity Income Fund', 'kdumphries14');
INSERT INTO page (page_handle, description, title, usert_handle) VALUES ('lmclanaghan15', 'orchestrate user-centric schemas', 'Bloomin&#39; Brands, Inc.', 'qdaouse15');
INSERT INTO page (page_handle, description, title, usert_handle) VALUES ('hcoat16', 'engage efficient e-tailers', 'iRobot Corporation', 'ddempsey16');
INSERT INTO page (page_handle, description, title, usert_handle) VALUES ('lleopold17', 'aggregate customized ROI', 'KCG Holdings, Inc.', 'fwitherow17');
INSERT INTO page (page_handle, description, title, usert_handle) VALUES ('mmanon18', 'unleash 24/7 convergence', 'CareDx, Inc.', 'abidewel18');
INSERT INTO page (page_handle, description, title, usert_handle) VALUES ('sbeaudry19', 'leverage compelling vortals', 'Communications Systems, Inc.', 'mattew19');
INSERT INTO page (page_handle, description, title, usert_handle) VALUES ('rshah1a', 'engineer bricks-and-clicks applications', 'Innocoll Holdings', 'kambrogelli1a');
INSERT INTO page (page_handle, description, title, usert_handle) VALUES ('rdayton1b', 'streamline front-end metrics', 'BB&T Corporation', 'onottle1b');
INSERT INTO page (page_handle, description, title, usert_handle) VALUES ('pglazer1c', 'exploit rich web services', 'Oasmia Pharmaceutical AB', 'bportchmouth1c');
INSERT INTO page (page_handle, description, title, usert_handle) VALUES ('adewdeny1d', 'envisioneer killer infrastructures', 'Expelled from Paradise', 'rhimsworth1d');